"""
Central enums for Sustainability & SDG Reporting Hub.

All enum values are stored in PostgreSQL as ENUM types via Alembic.
Keep names stable; changing values may require a data migration.
"""

import enum


class UserRole(str, enum.Enum):
    """Role of a user in the platform."""

    ADMIN = "ADMIN"
    DEPARTMENT_COORDINATOR = "DEPARTMENT_COORDINATOR"
    VIEWER = "VIEWER"


class DepartmentType(str, enum.Enum):
    """Type of department or organisational unit."""

    ACADEMIC = "ACADEMIC"
    OPERATIONS = "OPERATIONS"
    RESEARCH_CENTRE = "RESEARCH_CENTRE"
    OTHER = "OTHER"


class ReportingCycleStatus(str, enum.Enum):
    """Status of a reporting cycle."""

    DRAFT = "DRAFT"
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class ContributionType(str, enum.Enum):
    """Type of contribution (research, teaching, operations, etc.)."""

    RESEARCH = "RESEARCH"
    TEACHING = "TEACHING"
    OPERATIONS = "OPERATIONS"
    POLICY = "POLICY"
    COMMUNITY = "COMMUNITY"
    OTHER = "OTHER"


class ContributionStatus(str, enum.Enum):
    """Workflow status of a contribution."""

    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ReportSectionScopeType(str, enum.Enum):
    """Scope of a report section (SDG, department, theme, overall)."""

    SDG = "SDG"
    DEPARTMENT = "DEPARTMENT"
    THEME = "THEME"
    OVERALL = "OVERALL"


class ReportSectionStatus(str, enum.Enum):
    """Status of a report section draft."""

    DRAFT = "DRAFT"
    REVIEWED = "REVIEWED"
    FINAL = "FINAL"


class DraftGeneratedBy(str, enum.Enum):
    """Whether a draft was generated by AI or human."""

    AI = "AI"
    HUMAN = "HUMAN"
